version: '2'
services:
  frontend:
    build:
      context: ./FE/project_interview
      dockerfile: Dockerfile
    image: nguyntunphng/frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./BE/WebAPI
      dockerfile: Dockerfile
    image: nguyntunphng/backend:latest
    ports:
      - 7244:7244
    environment:



