version: '2'
services:
  frontend:
    build:
      context: ./FE/project_interview
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./BE/WebAPI
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: Movie
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - database
    command: bash -c "sleep 10 && dotnet ef database update && dotnet run"

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Movie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
