version: '1'
services:
  frontend:
    build:
      context: ./FE/project_interview/
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: ./BE/WebAPI/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=Movie;Username=postgres;Password=postgres;

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Movie
